### ISSUE TITLE
create pkgdown docs 

### ISSUE THREAD

**Issue by mattmalin** [randomcolour/randomcolourr#31]
(host generated docs through github pages, either as subdir in root or on separate gh-pages)

**Comment by mattmalin** [comment]
want to also ensure this is in docs directory and point github pages for repo at this directory

**Comment by jn8** [comment]
github page settings appear to be unavailable for our repo?

**Comment by mattmalin** [comment]
> github page settings appear to be unavailable for our repo?
I think just because of ownership settings of the organisation didn't include you - the settings are there and I can change them.

The documentation branch needs starting again without the additional junk files but let's also do this before CRAN release :)

**Comment by jn8** [comment]
Let me know once you've updated ownership and I'll try again. 

I'll get rid of the test doc files and re-generate docs with package down

**Comment by mattmalin** [comment]
it'll be set up eventually for the directory on master branch anyway, so we can change later once documentation overall looks good :)

**Comment by mattmalin** [comment]
Close with #33
